config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :log_users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }

  #resources :log_users

  resources :users do
      root 'users#index'
      get 'users/show'
      post 'users/create'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
mount_uploader :image, ImageUploader
# crop用の仮想attribute
  attr_accessor :image_crop_x
  attr_accessor :image_crop_y
  attr_accessor :image_crop_w
  attr_accessor :image_crop_h
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
     VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :mail_address, presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
validates :name, presence: true
validates :password, presence: true, length: { minimum: 8, message: "8文字以上で入力してください" }, format: { with: /\A[a-z0-9]+\z/i, message: "英数字で入力してください" }

has_many :user_category_relationships, dependent: :destroy, foreign_key: "user_id", inverse_of: :user
has_many :categories, through: :user_category_relationships
accepts_nested_attributes_for :categories
accepts_nested_attributes_for :user_category_relationships, :allow_destroy => true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  #before_action :sign_in_required, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @categories = @user.categories
  end

  # GET /users/new
  def new
    @user = User.new
    #@user.categories.build
    @user.user_category_relationships.build
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
          if params[:user][:image].blank?#画像がないときは、今までどおり更新
            format.html { redirect_to @user, notice: 'User was successfully created.' }
            format.json { render :show, status: :created, location: @user }
          else#画像があるときは、Cropに飛ばす。
            format.html { render :crop }
          end
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
          if params[:user][:image].blank?#画像がないときは、今までどおり更新
            format.html { redirect_to @user, notice: 'User was successfully updated.' }
            format.json { render :show, status: :ok, location: @user }
          else#画像があるときは、Cropに飛ばす。
            format.html { render :crop }
          end
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:mail_address, :name, :password, :image,
      :image_crop_x,
      :image_crop_y,
      :image_crop_w,
      :image_crop_h,
      category_ids: [])
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= simple_form_for @user, html: { class: "form form-horizontal user",multipart: true } do |f|
  .form-group
    = f.label :mail_address, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :mail_address, class: 'form-control', required: true
    = f.error_span(:mail_address)
  .form-group
    = f.label :name, class: 'control-label col-lg-2'
    .col-lg-10
      = f.text_field :name, class: 'form-control', required: true
    = f.error_span(:name)
  .form-group
    = f.label :password, class: 'control-label col-lg-2'
    .col-lg-10
      = f.password_field :password, class: 'form-control', required: true
    = f.error_span(:password)
  .form-group
    = f.association :categories, class: 'form-control', as: :select, multiple: true, include_blank: true, input_html:{class: 'searchable'}, required: true
    = f.error_span(:categories)
  .form-group
    = f.file_field :image, class: 'form-control'
    = f.error_span(:image)
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit nil,class: 'btn btn-primary'
      = link_to t('.cancel', :default => t("helpers.links.cancel")), users_path, :class => 'btn btn-default'

app/views/users/crop.haml
= simple_form_for @user, html: { class: "form form-horizontal user",multipart: true } do |f|
  .form-group
    = f.cropbox :image, width: 200, height: 200, input_html:{class: 'user_image_cropbox'}
  %h4= "プレビュー"
  .form-group
    = f.previewbox :image, width: 200, height: 200, input_html:{class: 'user_image_previewbox'}
  .form-group
    .col-lg-offset-2.col-lg-10
      = f.submit "Crop",class: 'btn btn-primary'

app/views/users/edit.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/index.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-stripid
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:image)
      %th= model_class.human_attribute_name(:mail_address)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:password)
      %th= model_class.human_attribute_name(:category_id)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @users.each do |user|
      %tr
      %td= link_to user.id, user_path(user)
      %td
        %ul
          -unless user.image.blank?
            %li= image_tag user.image.url(:thumb)
      %td= user.mail_address
      %td= user.name
      %td= user.password
      %td
        %ul
          - unless user.categories.blank?
            - user.categories.each do |i|
              %li= i.name
          - else
            %li= "none"
      %td=l user.created_at
      %td
        = link_to t('.show', :default => t("helpers.links.show")), user_path(user), :class => 'btn btn-default btn-xs'
        = link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(user), :class => 'btn btn-default btn-xs'
        = link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_user_path, :class => 'btn btn-primary'

app/views/users/new.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/users/show.html.haml
- model_class = User
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:mail_address) + ':'
  %br
  = @user.mail_address
%p
  %strong= model_class.human_attribute_name(:image) + ':'
  %br
  = image_tag @user.image.url
%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @user.name
%p
  %strong= model_class.human_attribute_name(:password) + ':'
  %br
  = "********"
%p
  %strong= model_class.human_attribute_name(:category_id) + ':'
  - unless @user.categories.blank?
    - @user.categories.each do |i|
      %br
      = i.name
  - else
    %br
    = "none"


= link_to t('.back', :default => t("helpers.links.back")), users_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_user_path(@user), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), user_path(@user), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'