config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :log_users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }

  #resources :log_users

  resources :users do
      root 'users#index'
      get 'users/show'
      post 'users/create'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    acts_as_nested_set

    has_many :user_category_relationships, dependent: :destroy, foreign_key: "category_id"
    has_many :users , through: :user_category_relationships, inverse_of: :category

    # ルートノードに移動させた場合は、parent_id は "#"になるので、
  # ルートに移動させる move_to_root メソッドを呼ぶ
  # 親ノードがある場合は、parent_id を 更新する
  def parent_id=(parent_id)
    if parent_id == '#'
      move_to_root
    else
      super(parent_id)
    end
  end

  # ルートノードに移動させた場合は、親ノード(parent)がnilのため、ルートの兄弟配列から移動先を特定する
  # 親ノードがある場合は、move_to_child_with_indexメソッドで移動する
  def new_position=(new_position)
    if parent.blank?
      prev_node = root.siblings[new_position.to_i - 1]
      move_to_right_of prev_node
    else
      move_to_child_with_index(parent, new_position.to_i)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :parent_id, :new_position)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.haml
= simple_form_for @category, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.error_span :name
  = f.label :parent_id
  = f.select :parent_id, nested_set_options(Category) {|i| "#{'-' * i.level} #{i.name}" }, { selected: @category.parent_id, include_blank: true }
  = f.button :submit, :class => 'btn-primary'
  = link_to t('.cancel', :default => t("helpers.links.cancel")), categories_path, :class => 'btn btn-default'

app/views/categories/edit.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/categories/index.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize

#jstree_categories

%br
%br

= link_to t('Create'), "#", :class => 'btn btn-success', :id => 'create_category'
= link_to t('Rename'), "#", :class => 'btn btn-warning', :id => 'rename_category'
= link_to t('Delete'), "#", :class => 'btn btn-danger',  :id => 'delete_category'

app/views/categories/new.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/categories/show.html.haml
- model_class = Category
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:name) + ':'
  %br
  = @category.name


= link_to t('.back', :default => t("helpers.links.back")), categories_path, :class => 'btn btn-default'
= link_to t('.edit', :default => t("helpers.links.edit")), edit_category_path(@category), :class => 'btn btn-default'
= link_to t('.destroy', :default => t("helpers.links.destroy")), category_path(@category), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'