config/routes.rb
Rails.application.routes.draw do
  resources :categories
  devise_for :log_users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }

  #resources :log_users

  resources :users do
      root 'users#index'
      get 'users/show'
      post 'users/create'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  </head>

  <body>
      <header>
            <nav>
                <% if log_user_signed_in? %>
                <strong><%= link_to current_log_user.username, users_path %></strong>
                <%= link_to 'プロフィール変更', edit_log_user_registration_path %>
                <%= link_to 'ログアウト', destroy_log_user_session_path, method: :delete %>
            <% else %>
                <%= link_to 'サインアップ', new_log_user_registration_path %>
                <%= link_to 'ログイン', new_log_user_session_path %>
                <% end %>
            </nav>
        </header>

      <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
      <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">×</a> <!-- アラートダイアログに×ボタンをつける -->
      <%= msg %>
      </div>
      <% end %>
      <%= yield %>
  </body>
</html>